---
name: RPM Build
on:
  release:
    types: [published]

jobs:

  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the package
        run: |
          mkdir -p {BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          sudo rpmbuild  --define "_topdir $(pwd)" --define "version ${{ github.event.release.tag_name }}" --define "myrepo ${{ github.repository_owner }}/${{ github.event.repository.name }}" -bb "red hat/tsn-testbench.spec"

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: RPMS/my-package-name_0.0.1-1.noarch.rpm
